engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc
  nodesecurity:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:

ratings:
   paths:
   - "**.js"
